"""time started at

Revision ID: 9b4f7c4732ee
Revises: a50da2f835ce
Create Date: 2023-05-09 00:01:53.831826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b4f7c4732ee'
down_revision = 'a50da2f835ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('started_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'started_at')
    # ### end Alembic commands ###
